# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Embedded Computer Systems I
author: Stan Baek, James Trimble
logo: ece382.png
copyright: '2022' # Copyright year to be placed in the footer

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  exclude_patterns          : []    # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)


# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: ece382.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/USAFA-ECE/ece382  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: favicon.ico
  use_issues_button: true
  use_repository_button: true
  extra_css:
    - custom.css

output: 
  html_document:
    number_sections: true
    
sphinx:
  config:
    numfig_secnum_depth: 0
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
      
  extra_extensions:   # A list of extra extensions to load by Sphinx.
    - sphinxcontrib.mermaid  
#   - sphinx_inline_tabs
    
parse:
  myst_enable_extensions:
    # for parsing of dollar $ and $$ encapsulated math.
    - dollarmath
    #  for direct parsing of amsmath LaTeX environments.
    - amsmath
    # To auto-detect HTML-like links in your markdown and convert them to hyperlinks.
    - linkify
    # To allow you to define markdown “variables” and substitute text in using them. See Substitutions and variables in markdown.
    - substitution
    # To allow you to use ::: fences for admonitions, in order to make them easier to render in interfaces that do not support MyST. See Markdown-friendly directives with :::.
    - colon_fence

# Add a "Launch on Google Colab" button to .ipynb files
launch_buttons:
  colab_url: "https://colab.research.google.com"
